default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: divedirectory_development
  
test:
  <<: *default
  database: divedirectory_test

production:
  <<: *default
  database: divedirectory_production
  username: divedirectory
  password: <%= ENV['DD_DATABASE_PASSWORD'] %>